on:
  push:
    branch: ["master"]

name: Publish to crates.io

jobs:
  build_and_test:
    name: Build the client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo build --release --all-features

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: cargo publish -p tinydancer --token ${CRATES_TOKEN} --no-verify
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
