on:
  push:
    branch: ["ci", "master"]

name: Publish to crates.io

jobs:
  build_and_test:
    name: Build the client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: rustup toolchain list
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

  check_and_publish:
    name: Check semver and publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: cargo publish -p tinydancer --token ${CRATES_TOKEN} --no-verify
        if: ${{CRATES_DEPLOY}}
        env:
          CRATES_DEPLOY: ${{ secrets.CRATES_DEPLOY }}
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
